image: ubuntu:19.04

test:
  only:
    # e.g.: any_check-X.Y.Z-rc.N, zk-1.15.0
    - /.*-\d+\.\d+\.\d+(-(rc|pre|alpha|beta)\.\d+)?$/
  script:
    - apt update -qy
    - apt install -y git python3-dev python3-pip
    - python3 --version
    - pip3 --version
    - pip3 install -U pip setuptools wheel
    - pip3 install datadog_checks_dev[cli]
    - ddev --version
    - ddev config set core .
    - git tag -a -m "tested-0.1.0" tested-0.1.0
    - aws --help
    # - if [ -n "$DD_TEST_CMD" ] ; then eval "$DD_TEST_CMD" ; else echo "skipping, DD_TEST_CMD is not set" ; fi
  tags: [ "runner:main", "size:large" ]
